### ISSUE TITLE
Consider if metadata SHOULD be optional or not

### ISSUE THREAD

**Issue by andreassolberg** [rohe/oidcfederation#18]
Roland has a use case to discuss

**Comment by rohe** [comment]
I have a use case where we on one hand has information producers and on the other hand information consumers. Pushing information from one to the other is done using HTTP PUT to an endpoint at the consumer. So apart from proving that a producer/consumer is part of the federation only 2 pieces of information is needed. The keys that the producer uses to signed the pushed information and the endpoint at the consumer. One could use metadata with a new non-standard type for this but that to me sounds a bit too complicated. We already have _jwks_ in the producers entity statement so the only thing we have to add is the _endpoint_ in the consumers entity statement.

**Comment by andreassolberg** [comment]
Makes sense. It is allowed to have an empty metadata claim:

```
"metadata": {}
```

Do you think we should allow to leave out the claim all together, with the same semantic meaning as to have an empty object?

**Comment by rohe** [comment]
Yes

**Comment by rohe** [comment]
This is dealt with in the last version (-07) of the draft
