### ISSUE TITLE
Simpler text suggestion

### ISSUE THREAD

**Issue by alejandro-perez** [rohe/oidcfederation#41]
https://github.com/rohe/oidcfederation/blob/3a6c54a818471fc16cc2343d0ce6003eb378161d/draft/oidcfed.hf.txt#L941-L944

I found this sentence a bit complex. I think this could be stated as follow (or similar):

```
Each entity statement in a trust chain is signed and MUST have a
           expiration time (exp) set. The expiration time of the whole trust
           chain is set to the minimum value of exp within the chain.
```

**Comment by rohe** [comment]
OK
