### ISSUE TITLE
Should this paragraph only affect to the mentioned protocols?

### ISSUE THREAD

**Issue by alejandro-perez** [rohe/oidcfederation#43]
https://github.com/rohe/oidcfederation/blob/3a6c54a818471fc16cc2343d0ce6003eb378161d/draft/oidcfed.hf.txt#L1026-L1029

I guess the text in this paragraph should be valid for any protocol, not only the two ones enumerated.

**Comment by rohe** [comment]
Correct! Added some text about this.
