### ISSUE TITLE
Use flatten() instead of sum()

### ISSUE THREAD

**Issue by alejandro-perez** [rohe/oidcfederation#44]
https://github.com/rohe/oidcfederation/blob/3a6c54a818471fc16cc2343d0ce6003eb378161d/draft/oidcfed.hf.txt#L1102

Since it's not a sum,but indeed a flattening, why not using `flatten(msn[n])`?

**Comment by rohe** [comment]
The whole thing about flattening is up for discussion so I'll close this for the time being.
Might reopen it if appropriate.
