### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by laskasn** [rohe/oidcfederation#61]
At 
2.2. Trust Chain
second bullet (not the numbered ones) you mention that
"There MUST always be a signing key carried in the jwks claim in ES[j] that can be used to verify the signature of ES[j-1], j=i,...,1 ."

My question is if, say, we have an hierarchy 
**TrustAnchor** -> **Organisation** -> **OP**  
then the chain should be : 
- OP self-signed entity statement 
- Organisation signs an entity statement about OP
- trustanchor signs an entity statement about organisation

the question is: 
which private key should Organisation use to sign the Entity statement, when we demand him to set at the jwks field the public key of his subordinate???  Shouldn't the Organisation sign it with his Private key and set at jwks its public counterpart, so as anyone who had this JWT could easily verify it's integrity? 

What i am not getting correctly? Could you explain a bit more the algorithm?

Thanks in advance!

**Comment by rohe** [comment]
Hi Nikolas!

> On 12 Nov 2020, at 17:43, Nikolas Laskaris <notifications@github.com> wrote:
> 
> 
> At
> 2.2. Trust Chain
> second bullet (not the numbered ones) you mention that
> "There MUST always be a signing key carried in the jwks claim in ES[j] that can be used to verify the signature of ES[j-1], j=i,...,1 ."
> 
> My question is if, say, we have an hierarchy
> TrustAnchor -> Organisation -> OP
> then the chain should be :
> 
> OP self-signed entity statement
> Organisation signs an entity statement about OP
> trustanchor signs an entity statement about organisation
> the question is:
> which private key should Organisation use to sign the Entity statement, when we demand him to set at the jwks field the public key of his subordinate??? Shouldn't the Organisation sign it with his Private key and set at jwks its public counterpart, so as anyone who had this JWT could easily verify it's integrity?
> 
The entity statement that can be verified by them self in a trust chain is the OP’s self-signed entity statement. All the others can only be verified using the keys that are published in the chain.

This is the bases for constructing trust in the whole chain.

You use keys you have received in some out-of-bands secure way to verify the trust anchors statement.
If that verifies OK you can use the JWKS in the trust anchors statement to verify the statement by the organisation.
If the organisations statement can be verified by the keys in the trust anchors statement the JWKS in the organisations
statement can then be used to verify the statement by the OP. If that verifies OK you have verified that the whole chain is OK.

Which basically means that the OP is part of the Organisation which is part of the federation, beside the fact that no one has
messed with the entity statements.

If the JWKS in the statement referred to the issuer you could verify that the entity statement hadn’t been tampered with but why would
you believe that the issuer was the one it said it was ? And why would you believe that it was part of the federation ?

You need the chain of verified signatures to be certain of those things.
> What i am not getting correctly? Could you explain a bit more the algorithm?
> 
Hope that was clear enough.

— Roland

There is nothing you cannot prove if your outlook is only sufficiently limited. (Dorothy L. Sayers, ”Whose body?”)

**Comment by laskasn** [comment]
Very nice explanation! It's now clear to me why this is constructed in such a way, it completely makes sense now!
Thanks a lot for spending your time and effort to explain!
